### ISSUE TITLE
ChromePathNotSetError

### ISSUE THREAD

**Issue by pquerner** [gladiatortoise/node-apiless-youtube-upload#34]
Only started coding, but I get this error very soon when selenium wants to do its job:

```
yt-upload-apiless-node-1  | ChromePathNotSetError
yt-upload-apiless-node-1  |     at new LauncherError (/home/node/app/node_modules/chrome-launcher/dist/utils.js:26:22)
yt-upload-apiless-node-1  |     at new ChromePathNotSetError (/home/node/app/node_modules/chrome-launcher/dist/utils.js:33:9)
yt-upload-apiless-node-1  |     at Object.linux (/home/node/app/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
yt-upload-apiless-node-1  |     at Function.getFirstInstallation (/home/node/app/node_modules/chrome-launcher/dist/chrome-launcher.js:117:51)
yt-upload-apiless-node-1  |     at Launcher.launch (/home/node/app/node_modules/chrome-launcher/dist/chrome-launcher.js:176:43)
yt-upload-apiless-node-1  |     at Object.launch (/home/node/app/node_modules/chrome-launcher/dist/chrome-launcher.js:37:20)
yt-upload-apiless-node-1  |     at Object.module.exports [as default] (/home/node/app/node_modules/find-chrome-version/index.js:35:39)
yt-upload-apiless-node-1  |     at ensureChromedriver (/home/node/app/node_modules/node-chromedriver-downloader/dist/index.js:96:104)
yt-upload-apiless-node-1  |     at makeWebDriver (/home/node/app/node_modules/node-apiless-youtube-upload/dist/helpers/makeWebDriver.js:51:87)
yt-upload-apiless-node-1  |     at exports.default (/home/node/app/node_modules/node-apiless-youtube-upload/dist/methods/uploadVideo.js:36:54) {
yt-upload-apiless-node-1  |   message: 'The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.',
yt-upload-apiless-node-1  |   code: 'ERR_LAUNCHER_PATH_NOT_SET'
yt-upload-apiless-node-1  | }
```

I am running it in a docker container:

```
version: "2"
services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - STREAMER=${STREAMER:?error}
    volumes:
      - ./:/home/node/app
    command: "npm start"
```
